language: elixir

elixir:
  - 1.4.0

otp_release:
  - 19.2

sudo: false

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix test
  - mix dialyze

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
